
package com.king.yyl.service.enums;

public enum PermissionType {
    VIEW_WORKSPACE, MODIFY_WORKSPACE, CREATE_WORKSPACE, DELETE_WORKSPACE, VIEW_PROJECT, MODIFY_PROJECT, CREATE_PROJECT, DELETE_PROJECT;
}
